name: MongoDB Backup Tool Tests

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Prepare test environment
        run: |
          mkdir -p backups
          mkdir -p test-backups
          echo "GITHUB_WORKSPACE=${GITHUB_WORKSPACE}" > .env
          echo "Проект находится в: ${GITHUB_WORKSPACE}"
          echo "Содержимое текущей директории:"
          ls -la

      - name: Setup Docker
        uses: docker/setup-buildx-action@v2

      - name: Verify Docker Compose version
        run: |
          # Проверяем версию Docker и Docker Compose
          docker --version
          docker compose version

          # Если docker compose не найден, установим классический docker-compose
          if ! docker compose version &>/dev/null; then
            echo "Устанавливаем docker-compose из репозитория..."
            sudo apt-get update
            sudo apt-get install -y docker-compose
          fi

      - name: Run tests with Docker
        run: |
          # Подготовка - сборка проекта и копирование файлов
          npm install
          npm run build
          cp -r dist test/
          cp -r node_modules test/
          cp package*.json test/
          cp tsconfig.json test/

          chmod +x test/run-tests.sh

          # Запуск контейнеров
          if docker compose version &>/dev/null; then
            docker compose -f test/docker-compose.test.yml up -d
          else
            docker-compose -f test/docker-compose.test.yml up -d
          fi

          docker ps
          echo "Проверяем логи контейнеров:"
          docker logs mongo-tools
          docker logs test-mongodb || echo "MongoDB контейнер ещё не запущен"
          echo "Запускаем тесты..."
          ./test/run-tests.sh || echo "Tests failed with exit code $?"

      - name: Verify build directory
        run: |
          echo "✅ Checking project structure..."
          [ -d dist ] && echo "✅ Build directory exists" || echo "❌ Build directory missing"
          [ -d src ] && echo "✅ Source directory exists" || echo "❌ Source directory missing"
          [ -f package.json ] && echo "✅ package.json exists" || echo "❌ package.json missing"

      - name: Test CLI interface
        run: |
          echo "✅ Testing CLI interface..."
          node ./dist/index.js --help
          echo "✅ CLI interface works"

      - name: Check TypeScript compilation
        run: |
          echo "✅ Checking TypeScript compilation..."
          tsc --noEmit
          echo "✅ TypeScript compilation OK"
