name: MongoDB Backup Tool Tests

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Create test directories
        run: |
          mkdir -p backups
          mkdir -p test-backups

      - name: Setup Docker
        uses: docker/setup-buildx-action@v2

      - name: Run tests with Docker
        run: |
          chmod +x test/run-tests.sh
          ./test/run-tests.sh || echo "Tests failed with exit code $?"

      - name: Save test logs
        if: always()
        run: |
          echo "=== TEST LOGS ===" >> $GITHUB_STEP_SUMMARY
          if [ -f test/mongodb-backup-test.log ]; then
            cat test/mongodb-backup-test.log >> $GITHUB_STEP_SUMMARY
          else
            echo "No test logs found" >> $GITHUB_STEP_SUMMARY
          fi
